name: Publish site
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
env:
  BASEURL: https://ground1363.github.io/davidmakestad-site/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - run: |
          pwd
          ls -la
          echo "CONFIG:"
          test -f config.toml && sed -n '1,120p' config.toml || echo "config.toml NOT FOUND"
          echo "TREE (possible capitalized dirs):"
          git ls-tree -r --name-only HEAD | grep -E '^(Layouts/|Content/|Static/|Themes/)' || true
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.2'
          extended: true
      - run: |
          hugo version
          hugo --minify --baseURL "${BASEURL}" -s . -d public -v
      - run: |
          echo "PUBLIC DIR:"
          ls -la public || true
          echo "---"
          ls -la public/tekster || true
      - run: test -f public/index.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
